config/routes.rb
Rails.application.routes.draw do
  scope "(/:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      devise_for :admin_users, controllers: {
        sessions: 'admin/admin_users/sessions',
      }
      resources :users do
        collection do
          get :reports
          get :make_admin
          get :multiple_collection_hide
        end

        member do
          get :collections
          post :collection_hide
          get :approve
          get :deny
          get :enable
          get :verify
          post :remove_custom_tab
          get :nft_contracts
          post :hide_contracts
        end
      end
      resources :categories
      resources :fees
      resources :featured_users, except: [:edit, :update]
      resources :featured_collections, except: [:edit, :update]
      resources :transactions, only: [:index]
      get 'setting', to: 'setting#recent_hours'
      post 'setting', to: 'setting#update_recent_hours'
      get 'dashboard', to: 'dashboard#index'
      root to: 'dashboard#index'
    end

    resources :users, except: [:index, :create, :destroy] do
      collection do
        get :following
        get :follow
        get :unfollow
        get :load_tabs
        post :like
        post :unlike
        post :bid
        post :report
        post :create_contract
        delete :remove_nft_contract
      end

      member do
        post :collection_hide
      end
    end

    resources :nft_contracts, only: [:show]

    resources :collections, only: [:new, :show, :create]  do
      member do
        get :remove_from_sale
        get :fetch_details
        get :fetch_transfer_user
        post :bid
        post :buy
        post :sell
        post :update_token_id
        post :update_hash
        post :change_price
        post :transfer_token
        post :sign_metadata_hash
        post :sign_fixed_price
        post :owner_transfer
        post :burn
        post :add_comment
      end
    end

    resources :sessions, only: [:create, :destroy] do
      collection do
        get :valid_user
      end
    end
    resources :likes, only: [:create, :update]
    resources :bids
    resources :fees

    ### CUSTOM ROUTES
    get 'dashboard', to: 'dashboard#index'
    get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
    get 'owncollections', to: 'dashboard#collectionitemlists'
    get 'collections_sort', to: 'dashboard#sorted_by_price_or_title'
    get 'my_items', to: 'users#my_items'
    get 'activities', to: 'activities#index'
    post 'create_custom_tab', to: 'activities#create_custom_tab'
    delete 'remove_custom_tab', to: 'activities#remove_custom_tab'
    post 'assign_tab_to_activity', to: 'activities#assign_tab_to_activity'
    # get 'load_more_activities', to: 'activities#load_more'
    get 'search', to: 'dashboard#search'
    get 'notifications', to: 'dashboard#notifications'
    get 'contract_abi', to: 'dashboard#contract_abi'
    get 'category_filter', to: 'dashboard#set_categories_by_filter'
    get 'gas_price', to: 'dashboard#gas_price'
    get 'all_notifications', to: 'dashboard#all_notifications'

    ### STATIC PAGES
    get 'about', to: 'static#about'
    get 'faq', to: 'static#faq'
    get 'terms_conditions', to: 'static#terms_conditions'
    get 'privacy', to: 'static#privacypolicy'

    ### ROOT PAGE
    root to: "dashboard#index"

    ### THIRD-PARTY ROUTES
    require 'sidekiq/web'
    authenticated do
      mount Sidekiq::Web => '/sidekiq'
    end
    get '/:username', to: 'users#artist', constraints: { username: /[^\/]+/ }
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:show]
  skip_before_action :is_approved, only: [:show]
  # before_action :set_collection, only: [:show, :bid, :execute_max_bid, :remove_from_sale, :execute_bid, :buy]
  before_action :set_collection, except: [:new, :create, :update_hash, :update_token_id, :sign_metadata_hash, :add_comment]

  skip_before_action :verify_authenticity_token


  def new
    @collection_type = params[:type]
  end

  def show
    @tab = params[:tab]
    @activities = PaperTrail::Version.where(item_type: "Collection", item_id: @collection.id).order("created_at desc")
    @max_bid = @collection.max_bid
    set_collection_gon
    @transactions = @collection.get_collections(false)
    @comments = @collection.comments
  end

  def create
    begin
      # ActiveRecord::Base.transaction do
        @collection = Collection.new(collection_params)
        @collection.state = :pending
        # ITS A RAND STRING FOR IDENTIFIYING THE COLLECTION. NOT CONTRACT ADDRESS
        @collection.address = Collection.generate_uniq_token
        @collection.creator_id = current_user.id
        @collection.owner_id = current_user.id
        @collection.royalty = 0 unless @collection.royalty.present?
        @collection.data = JSON.parse(collection_params[:data]) if collection_params[:data].present?
        @collection.owned_tokens = @collection.no_of_copies
        if @collection.valid?
          @collection.save
          @metadata_hash = Api::Pinata.new.upload(@collection)
          # PaperTrail.request(enabled: false) { @collection.approve! }
        else
          @errors = @collection.errors.full_messages
        end
      # end
    rescue Exception => e
      Rails.logger.warn "################## Exception while creating collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def bid
    begin
      @collection.place_bid(bid_params)
    rescue Exception => e
      Rails.logger.warn "################## Exception while creating BID ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def remove_from_sale
    if @collection.is_owner?(current_user)
      @collection.remove_from_sale
      @collection.cancel_bids
    end
    redirect_to collection_path(@collection.address)
  end

  def sell
    begin
      ActiveRecord::Base.transaction do
        @redirect_address = @collection.execute_bid(params[:address], params[:bid_id], params[:transaction_hash]) if @collection.is_owner?(current_user)
      end
    rescue Exception => e
      Rails.logger.warn "################## Exception while selling collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def buy
    begin
      ActiveRecord::Base.transaction do
        @redirect_address = @collection.direct_buy(current_user, params[:quantity].to_i, params[:transaction_hash])
      end
    rescue Exception => e
      Rails.logger.warn "################## Exception while buying collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def update_token_id
    # Make sure the collection belongs to the current_user
    collection = current_user.collections.unscoped.where(address: params[:collectionId]).take
    # collection should still be pending (minting just ended)
    return unless collection.pending?
    collection.approve! unless collection.instant_sale_price.present?
    collection.update(token: params[:tokenId])
    Notification.notify_mint_success(collection)
  end

  def update_hash
    # Make sure the collection belongs to the current_user
    collection = current_user.collections.unscoped.where(address: params[:collectionId]).take
    # collection should still be pending (minting just began)
    return unless collection.pending?
    # the refund job is registered once at the start of the minting transaction
    # if necessary, this job will wait for at most 10 minutes for calls to
    # 'update_token_id' and 'signed_fixed_price'
    if !collection.fee_refunded && collection.txn_hash.nil?
      ApplicationController.helpers.custom_error_flash('Minting Refund process running', 'error')
      RefundMintingFeeJob.perform_in(3.minutes, collection.id)
    end
    if !collection.nft_contract&.refund_fee && !collection.nft_contract&.txn_hash.nil? && !collection.nft_contract.shared?
      ApplicationController.helpers.custom_error_flash('Refund contract process running', 'error')
      RefundContractFeeJob.perform_in(3.minutes, collection.id)
    end
    # register the hash sent by the most recent call to update_hash
    # at this stage 2 calls are expected:
    # - hash at minting start
    # - hash at minting success if different
    if params[:txnHash].present?
      collection.update(txn_hash: params[:txnHash])
    end
  end

  def change_price
    @collection.assign_attributes(change_price_params)
    @collection.save
  end

  def burn
    if @collection.multiple?
      all_collections = Collection.where(nft_contract_id: @collection.nft_contract_id, token: @collection.token)
      #Using UPDATE_ALL to FORCE-skip cases where no_of_copies > owned_tokens for a brief moment 
      all_collections.update_all(:no_of_copies => @collection.no_of_copies - params[:supply].to_i)
      if @collection.owned_tokens == params[:supply].to_i #User has 2 actions, BURN ALL vs BURN some!
        @collection.burn! if @collection.may_burn?
      else
        @collection.update(:owned_tokens => @collection.owned_tokens - params[:supply].to_i)
      end 
    else   
      @collection.burn! if @collection.may_burn?
    end
  end

  def transfer_token
    new_owner = User.find_by_address(params[:user_id])
    if new_owner.present?
      @collection.hand_over_to_owner(new_owner.id)
    else
      @errors = [t("collections.show.invalid_user")]
    end
  end

  def sign_metadata_hash
    sign = if params[:contract_address].present?
      collection = current_user.collections.unscoped.where(address: params[:id]).first
      obj = Utils::Web3.new
      obj.sign_metadata_hash(params[:contract_address], collection.metadata_hash, current_user.address)
    else
      ""
    end
    render json: sign
  end

  def fetch_details
    render json: {data: @collection.fetch_details(params[:bid_id], params[:erc20_address])}
  end

  def add_comment
    collection = Collection.find_by(id: params[:id])
    comment = collection.comments.new(user_id: @current_user.id, description: params[:comment][:description])

    unless comment.save
      flash[:error] = comment.errors.full_messages
    end
    redirect_to collection_path(collection.address)
  end

  def fetch_transfer_user
    user = User.validate_user(params[:address])
    if @collection.owner.eql?(user)
      render json: {error: 'Impossible to transfer to the sender'}
    elsif user && user.is_approved? && user.is_active?
      render json: {address: user.address}
    else
      render json: {error: 'User not found or not activated yet. Please provide address of the user registered in the application'}
    end
  end

  def sign_fixed_price
    collection = current_user.collections.unscoped.where(address: params[:id]).take
    collection.approve! if collection.pending?
    collection.update(sign_instant_sale_price: params[:sign])
  end

  def owner_transfer
    collection = current_user.collections.where(address: params[:id]).take
    recipient_user = User.where(address: params[:recipient_address]).first
    if collection.multiple?
      collection.hand_over_to_owner(recipient_user.id, params[:transaction_hash], params[:supply].to_i)
    else 
      collection.hand_over_to_owner(recipient_user.id, params[:transaction_hash], collection.owned_tokens)
    end
  end
  private

  # Collection param from React  
  # def collection_params
  #   params.permit(:name, :description, :collection_address, :put_on_sale, :instant_sale_price, :unlock_on_purchase,
  #     :collection_category, :no_of_copies, :attachment)
  # end

  def collection_params
    params['collection']['category'] = params['collection']['category'].present? ? params['collection']['category'].split(",") : []
    params['collection']['nft_contract_id'] = NftContract.get_shared_id(params[:collection][:collection_type]) if params['chooseCollection'] == 'nft'
    params['collection']['nft_contract_id'] = NftContract.find_by_address(params['chooseOwnCollection'])&.id if params['chooseOwnCollection']!= 'new' && params['chooseCollection'] == 'create'
    params['collection']['erc20_token_id'] = Erc20Token.where(address: params[:collection][:currency]).first&.id if params[:collection][:currency].present?
    params.require(:collection).permit(:name, :description, :collection_address, :put_on_sale, :instant_sale_enabled, :instant_sale_price, :unlock_on_purchase,
                               :bid_id, :no_of_copies, :attachment, :cover, :data, :collection_type, :royalty, :nft_contract_id, :unlock_description,
                               :erc20_token_id, :country, category: [])
  end

  def change_price_params
    params[:collection][:put_on_sale] = false if params[:collection][:put_on_sale].nil?
    params[:collection][:unlock_on_purchase] = false if params[:collection][:unlock_on_purchase].nil?
    unless params[:collection][:instant_sale_enabled]
      params[:collection][:instant_sale_enabled] = false
      params[:collection][:instant_sale_price] = nil
    end

app/helpers/collections_helper.rb
module CollectionsHelper
  def cover_url(collection, variation = nil)
    return '/assets/dummy-image.jpg' if unauthorized_to_show_attachment(collection)
    attachment = ['image/png', 'image/jpeg', 'image/gif', 'image/webp'].include?(collection.attachment.content_type) ? collection.get_attachment(current_user) : collection.cover
    variant = attachment.present? ?
      ((variation.nil? || !attachment.variant(Collection::MEDIA_VARIANTS[variation]).processed?) ?
         attachment
         : attachment.variant(Collection::MEDIA_VARIANTS[variation]).processed
      ): nil
    variant.nil? ? '/assets/banner-1.png' : url_for(variant)
    # pinata_url(collection)
  end
  

  def attachment_tag(collection)
    attachment = collection.attachment
    return image_tag '/assets/dummy-image.jpg', class: "img-responsive" if unauthorized_to_show_attachment(collection)

    if ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
      audio_tag url_for(attachment), size: "550x400", controls: true
    elsif ['video/mp4', 'video/webm'].include?(attachment.content_type)
      video_tag url_for(attachment), class: "video-responsive", controls: true, autoplay: "", loop: "", muted: ""
    else
      # image_tag pinata_url(collection), class: "img-responsive"
      image_tag url_for(collection.get_attachment(current_user)), class: "img-responsive"
    end
  end

  def cover_tag(collection)
    attachment = collection.attachment
    if ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
      image_tag cover_url(collection), class: "img-responsive"
    end
  end

  def unauthorized_to_show_attachment(collection)
    # collection.unlock_on_purchase? && (!current_user.present? || (current_user && current_user != collection.owner))
    return false
  end

  def pinata_url(collection)
    collection.image_hash.present? ? "https://gateway.pinata.cloud/ipfs/#{collection.image_hash}" : '/assets/dummy-image.jpg'
  end

  def is_audio_collection?(attachment)
    ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
  end

  def contract_path(collection)
    return 'javascript:void(0)'if collection.nft_contract.shared? 
    
    nft_contract_path(:id => collection.nft_contract.address)
  end
end

app/views/collections/_accept_bid.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart acceptBidStart fa fa-check-circle grey"></i>
    <i class="allProgress acceptBidProgress fa fa-spinner fa-pulse hide"></i>
    <i class="allDone acceptBidDone fa fa-check-circle hide"></i>
    <i class="allRetry acceptBidRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h4><%= t('shared.accept_bid')%></h4>
    <p class="para-color"><%= t('shared.transaction_with_wallet')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart acceptBidStart disabledLink grey"><%= t('shared.start')%></a>
    <a href="javascript:void(0)" class="allProgress acceptBidProgress disabledLink hide"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="allDone acceptBidDone disabledLink hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="allRetry acceptBidRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_approve_execute_bid.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart approveExecbidStart fa fa-check-circle hide grey"></i>
    <i class="allProgress approveExecbidProgress fa fa-spinner fa-pulse"></i>
    <i class="allDone approveExecbidDone fa fa-check-circle hide"></i>
    <i class="allRetry approveExecbidRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h4><%= t('collections.show.approve')%></h4>
    <p class="para-color"><%= t('collections.show.approve_terms')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart approveExecbidStart disabledLink hide grey"><%= t('shared.start')%></a>
    <a href="javascript:void(0)" class="allProgress approveExecbidProgress disabledLink"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="allDone approveExecbidDone disabledLink hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="allRetry approveExecbidRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_collection_type.html.erb
<section class="create-collectible-section pt-20 pb-20">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="create-collectible-box">
          <div class="create-collectible-box-header">
            <div class="heading-create-collectible main__title">
              <h2 class="mt-0 mb-0"><%= t('collections.form.create_collectible')%></h2>
              <a href="javascript:history.back()"><%= t('shared.go_back')%></a>
            </div>
          </div>
          <div class="create-collectible-box-body">
            <p class="pt-20"><%= t('collections.form.collection_type_text')%></p>
            <p class="pt-20"><%= t('collections.form.collection_type_txt')%></p>

            <div class="create-collectible-button-box">
              <a class="single-multiple-create" href="<%= new_collection_path(type: "single")%>">
                <%= image_tag "single.png" %>
                <p><%= t('collections.form.single')%></p>
              </a>
              <a class="single-multiple-create" href="<%= new_collection_path(type: "multiple") %>">
                <%= image_tag "multiple.png" %>
                <p><%= t('collections.form.multiple')%></p>
              </a>
            </div>
            <p><%= t('collections.form.collection_privacy')%></p>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/collections/_comments.html.erb
<% if comments.present? %>
  <% comments.each do |comment| %>
    <div class="asset__desc comment">        
      <p class="content_details"><%= comment.description %></p>
      <p>By @<%= link_to comment.user.address, user_path(comment.user) %></p>
      <p class="content_details">at <%= comment.created_at.strftime('%d/%m/%y')%></p>
    </div>
  <% end %>
<% else %>
  <%= t("collections.show.no_records") %>
<% end %>

app/views/collections/_deploy_contract.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="deployProgress fa fa-spinner fa-pulse"></i>
    <i class="deployDone fa fa-check-circle hide"></i>
    <i class="deployRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h3><%= t('collections.form.deploy_contract')%></h3>
    <p class="para-color"><%= t('collections.form.deploy_contract_msg')%></p>
    <p class="refund_cap_transfer"><%= t('collections.show.contract_fees_refund', refund_transfer_cap: Fee.MaxRefundOwnerCollectionFee.last&.refund_fee_cap.to_f.round(3)) %></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="deployProgress disabledLink"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="deployDone hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="deployRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_own_contract.html.erb
<%unless blank==true%>
    <label class="radio-img">
        <%= radio_button_tag 'chooseOwnCollection', contract.address, nil, class: "chooseCollectionErc" %>
        <div class="image">
            <div class="icon-style-choose-collection">
            <span class="color-break"><%=image_tag contract.attachment_url, class: "img-responsive"%></span>
            </div>
            <div class="label-style-choose-collection">
            <label><%=contract.symbol%></label>
            </div>
            <div class="para-style-choose-collection">
            <p class="para-color"><%=contract.name%></p>
            </div>
        </div>
    </label>
<%else%>
    <label class="radio-img">
        <%= radio_button_tag 'chooseOwnCollection', 'new', true, class: "chooseCollectionErc" %>
        <div class="image">
            <div class="icon-style-choose-collection">
            <span>+</span>
            </div>
            <div class="label-style-choose-collection">
            <label>Create</label>
            </div>
            <div class="para-style-choose-collection">
            <p class="para-color">Your own new collection</p>
            </div>
        </div>
    </label>
<%end%>

app/views/collections/_owner.html.erb
<div class="token-collections">
  <div class="token-collections-images">
    <a href="<%= collection_path(collection.address)%>">
      <%= image_tag url_for(collection.owner.profile_image(:icon)), class: 'img-responsive' %>
      <i class="fa fa-check-circle"></i>
    </a>
  </div>
  <div class="token-collections-details">
    <a href="<%= collection_path(collection.address)%>">
      <p class="para-color"><%= t('collections.show.owner_token', token: (collection.owned_tokens || 1 ))%></p>
    </a>
    <div class="same_line_data">
      <a href="<%= link_to_user(collection.owner) %>" data-toggle="tooltip" data-placement="top" title="<%= collection.owner.address %>"><%= collection.owner.full_name_without_masked %></a>
      <button class='copy_nft_address' value="<%= collection.owner.address %>" data-toggle='tooltip' data-placement='right' title='Copy'><i class='fa fa-copy'></i></button>
    </div>
  </div>
</div>

app/views/collections/_price_change.html.erb
<div id="change-price" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title share_link_page_h4"><%= t('collections.show.change_price') %></h4>
  <%= form_tag(change_price_collection_path, method: :post, remote: true, class: 'change-price-form') do %>
    <%= hidden_field_tag 'id', @collection.address, class: 'nft-detail-name' %>


    <div class="modal-body">
      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-12">
          <label><%= t('shared.put_on_sale') %></label>
          <p class="para-color"><%= t('shared.pos_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-12">
          <label class="switch">
            <% if @collection.put_on_sale? %>
              <input type="checkbox" name="collection[put_on_sale]" id="collection-put-on-sale" checked>
            <% else %>
              <input type="checkbox" name="collection[put_on_sale]" id="collection-put-on-sale">
            <% end %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-12">
          <label><%= t('shared.instant_sale_price') %></label>
          <p class="para-color"><%= t('shared.instant_sale_price_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-12">
          <label class="switch">
            <input type="checkbox" id="collection_instant_sale_enabled" prevVal="<%= @collection.instant_sale_enabled %>" name="collection[instant_sale_enabled]" <%= 'checked' if @collection.instant_sale_enabled %>>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <div id='instPrice' class="row mb-15 <%= 'hide' unless @collection.instant_sale_price.present? %>">
        <div class="col-sm-12">
          <div class="form-group bidBuyInputs bordered">
            <div>
              <input type="text" name="collection[instant_sale_price]" prevVal="<%= @collection.instant_sale_price %>" value="<%= @collection.instant_sale_price %>" class="form-control input-custom sign__input" id="instant-price" placeholder="Enter price for one piece"/>
            </div>
            <div>
              <%= select_tag "collection[erc20_token_id]", options_for_select(Erc20Token.select_options, @collection.erc20_token_id), class: "form-control input-custom sign__input", required: true, prevVal: @collection.erc20_token_id %>
            </div>
          </div>
        </div>
      </div>

      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-12">
          <label><%= t('shared.unlock_one_purchased') %></label>
          <p class="para-color"><%= t('shared.unlock_one_purchased_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-12">
          <label class="switch">
            <% if @collection.unlock_on_purchase? %>
              <input type="checkbox" name="collection[unlock_on_purchase]" id="collection-unlock-on-purchase" checked>
            <% else %>
              <input type="checkbox" name="collection[unlock_on_purchase]" id="collection-unlock-on-purchase">
            <% end %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>
      <div class="row mb-15 unlock-description-section <%= 'hide' unless @collection.unlock_on_purchase? %>">
        <div class="col-md-8 col-sm-8 col-12">
          <label><%= t('collections.show.unlock_description') %></label>
        </div>
        <div class="col-md-12">
          <div class="form-group">
            <input type="text" name="collection[unlock_description]" class="form-control input-custom sign__input" id="collection-unlock-description" placeholder="Enter unlock description" value="<%= @collection.unlock_description %>"/>
          </div>
        </div>
      </div>

    </div>
    <div class="modal-footer change-price-footer">
      <%= submit_tag 'Update', class: 'hide', id: 'submitPriceChange', 'data-disable-with': "<i class='fa fa-spinner fa-spin'></i> Updating...".html_safe %>
      <a class="btn bidding-element-btn triggerPriceChange theme-btn" href="javascript:void(0)" role="button">Update</a>
      <a class="bidding-element-btn secondary-btn" data-dismiss="modal" role="button">Cancel</a>
    </div>
  <% end %>
</div>


<div class="zoom-anim-dialog mfp-hide modal sm_modal" id="priceChange">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title share_link_page_h4"><%= t('shared.follow_steps') %></h4>
  <div class="modal-body">

    <div class="approveFlow">
      <%= render partial: 'approve' %>
    </div>

    <div class="signFixedPrice hide">
      <%= render partial: 'sign_fixed_price' %>
    </div>
  </div>
</div>

app/views/collections/_put_on_sale.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart putOnSaleStart fa fa-check-circle grey"></i>
    <i class="allProgress putOnSaleProgress fa fa-spinner fa-pulse hide"></i>
    <i class="allDone putOnSaleDone fa fa-check-circle hide"></i>
    <i class="allRetry putOnSaleRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h4>Put on sale</h4>
    <p class="para-color">Sign message to put on sale</p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart putOnSaleStart disabledLink grey">Start</a>
    <a href="javascript:void(0)" class="allProgress putOnSaleProgress disabledLink hide">In Progress..</a>
    <a href="javascript:void(0)" class="allDone putOnSaleDone hide">Done</a>
    <a href="javascript:void(0)" class="allRetry putOnSaleRetry hide">Try again</a>
  </div>
</div>

app/views/collections/_success.html.erb
<div className="follow-step-block">
    <div class="follow-step-icon">
      <i class="fa fa-check-circle"></i>
    </div>
    <div class="follow-step-content">
      <h4><%= t('collections.collection')%></h4>
      <p class="para-color"><%= t('collections.successfully_minted')%></p>
    </div>
    <div class="follow-step-button themeBG">
      <a href="<%= my_items_path %>"><%= t('shared.go_to_my_items')%></a>
    </div>
</div>