config/routes.rb
Rails.application.routes.draw do
  scope "(/:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      devise_for :admin_users, controllers: {
        sessions: 'admin/admin_users/sessions',
      }
      resources :users do
        collection do
          get :reports
          get :make_admin
          get :multiple_collection_hide
        end

        member do
          get :collections
          post :collection_hide
          get :approve
          get :deny
          get :enable
          get :verify
          post :remove_custom_tab
          get :nft_contracts
          post :hide_contracts
        end
      end
      resources :categories
      resources :fees
      resources :featured_users, except: [:edit, :update]
      resources :featured_collections, except: [:edit, :update]
      resources :transactions, only: [:index]
      get 'setting', to: 'setting#recent_hours'
      post 'setting', to: 'setting#update_recent_hours'
      get 'dashboard', to: 'dashboard#index'
      root to: 'dashboard#index'
    end

    resources :users, except: [:index, :create, :destroy] do
      collection do
        get :following
        get :follow
        get :unfollow
        get :load_tabs
        post :like
        post :unlike
        post :bid
        post :report
        post :create_contract
        delete :remove_nft_contract
      end

      member do
        post :collection_hide
      end
    end

    resources :nft_contracts, only: [:show]

    resources :collections, only: [:new, :show, :create]  do
      member do
        get :remove_from_sale
        get :fetch_details
        get :fetch_transfer_user
        post :bid
        post :buy
        post :sell
        post :update_token_id
        post :update_hash
        post :change_price
        post :transfer_token
        post :sign_metadata_hash
        post :sign_fixed_price
        post :owner_transfer
        post :burn
        post :add_comment
      end
    end

    resources :sessions, only: [:create, :destroy] do
      collection do
        get :valid_user
      end
    end
    resources :likes, only: [:create, :update]
    resources :bids
    resources :fees

    ### CUSTOM ROUTES
    get 'dashboard', to: 'dashboard#index'
    get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
    get 'owncollections', to: 'dashboard#collectionitemlists'
    get 'collections_sort', to: 'dashboard#sorted_by_price_or_title'
    get 'my_items', to: 'users#my_items'
    get 'activities', to: 'activities#index'
    post 'create_custom_tab', to: 'activities#create_custom_tab'
    delete 'remove_custom_tab', to: 'activities#remove_custom_tab'
    post 'assign_tab_to_activity', to: 'activities#assign_tab_to_activity'
    # get 'load_more_activities', to: 'activities#load_more'
    get 'search', to: 'dashboard#search'
    get 'notifications', to: 'dashboard#notifications'
    get 'contract_abi', to: 'dashboard#contract_abi'
    get 'category_filter', to: 'dashboard#set_categories_by_filter'
    get 'gas_price', to: 'dashboard#gas_price'
    get 'all_notifications', to: 'dashboard#all_notifications'

    ### STATIC PAGES
    get 'about', to: 'static#about'
    get 'faq', to: 'static#faq'
    get 'terms_conditions', to: 'static#terms_conditions'
    get 'privacy', to: 'static#privacypolicy'

    ### ROOT PAGE
    root to: "dashboard#index"

    ### THIRD-PARTY ROUTES
    require 'sidekiq/web'
    authenticated do
      mount Sidekiq::Web => '/sidekiq'
    end
    get '/:username', to: 'users#artist', constraints: { username: /[^\/]+/ }
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # skip_before_action :authenticate_user, only: :index
  skip_before_action :is_approved

  def index
    current_user.custom_tabs.find_or_create_by(tab_name: 'Discarded')
    @nft_filter = true if params[:activity_type] == "blank"
    cookies.permanent["#{current_user.address.last(5)}_thumbnail_type"] = params[:thumbnail_type] || cookies["#{current_user.address.last(5)}_thumbnail_type"] || 'mini_thumbnail'
    #@thumbnail_type = cookies.permanent["#{current_user.address.last(5)}_thumbnail_type"]
    @thumbnail_type = params[:thumbnail_type].eql?('thumbnail') ? 'thumbnail' : 'mini_thumbnail'
    
    load_activities
  end

  def load_activities
    @page_no = params[:page_no] || 1
    @activities = if current_user.present?
      ApplicationController.helpers.get_activities(params[:activity_type], current_user, params[:filters]).paginate(page: @page_no, per_page: 20)
    else
      filter = params[:filters] || []
      User.default_activities(filter, @page_no)
    end
  end

  def create_custom_tab
    custom_tab = current_user.custom_tabs.new(tab_name: params[:tab_name])
    if custom_tab.save
      redirect_to activities_path(activity_type: "blank"), notice: "NFT file successfully created."
    else
      redirect_to activities_path(activity_type: "blank"), alert: custom_tab.errors.full_messages.compact * ' and '
    end
  end

  def assign_tab_to_activity
    activity_tab = if params[:item_type] == 'nft'
      current_user.activity_custom_tabs.find_by(nft_id: params[:item_id])
    else
      current_user.activity_custom_tabs.find_by(follow_id: params[:item_id])
    end

    if params[:tab_id].present? && params[:tab_id] != 'show'
      if activity_tab.present?
        activity_tab.update(custom_tab_id: params[:tab_id])
      else
        activity_tab = ActivityCustomTab.new(custom_tab_id: params[:tab_id])
        if params[:item_type] == 'nft'
          activity_tab.nft_id = params[:item_id]
        else
          activity_tab.follow_id = params[:item_id]
        end
        activity_tab.save
      end
    else
      activity_tab&.destroy
    end  
  end

  def remove_custom_tab
    if params[:tab_id].present?
      current_user.custom_tabs.destroy(params[:tab_id])
    end
    redirect_to activities_path(activity_type: "activity", filters: 'minted')
  end
end

app/views/activities/_activities.html.erb
<% @activities.each do |activity| %>
  <% if params[:filters] == "my_collections"%>
    <%= render 'activities/own_contract', contract: activity %>
  <%else%>
    <% if activity.item.present? %>
      <%= render activity.item_type.downcase, activity: activity if ["Follow", "Like", "Collection", "Bid"].include?(activity.item_type) %>
    <% end %>
  <%end%>
<% end %>

app/views/activities/_bid.html.erb
<%# if activity.event == "create" && activity.item.user.present? && activity.item.collection.present? %>
<% if activity.item.user.present? && activity.item.collection.present? && (activity.event == 'create' ||
   (activity.event == 'update' && activity.changeset.keys.include?("state") && ["executed", "expired"].include?(activity.changeset["state"].last))) %>
  <% bid = activity.item %>
  <% cover_image = bid.collection.cover.present? ? bid.collection.cover : bid.collection.attachment %>
  <% custom_tab = selected_tab(current_user, activity.item.collection) %>
  <% custom_tab_options = current_user.custom_tabs.map{|u| [u.tab_name, u.id]} %>
  <% custom_tab_options << ['Show', 'show'] if custom_tab&.tab_name == 'Discarded' %>
  <% if activity.event == 'create' %>
    <%if @thumbnail_type.eql?('mini_thumbnail') %>
      <div class="activity">
        <div class="activity__cover <%= @thumbnail_type.eql?('mini_thumbnail') ? '' : 'thumbnail_cover' %>">
          <a class="lightbox" href="<%= url_for(cover_image) %>" data-lightbox="image-1">
            <div class="lightbox_custom ">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 512 512">
                <g>
                  <g>
                    <path d="m499.4,250.8c-51-86.3-143.6-140.4-243.4-140.4s-192.5,54.1-243.4,140.4c-2.1,3.1-2.1,7.3 5.32907e-15,10.4 51,86.3 143.6,140.4 243.4,140.4s192.5-54.1 243.4-140.4c2.1-3.1 2.1-7.3 0-10.4zm-243.4,130c-90.5,0-174.8-47.8-221.6-124.8 46.8-77 131.1-124.8 221.6-124.8s174.8,47.8 221.6,124.8c-46.8,77-131.1,124.8-221.6,124.8z"/>
                    <path d="m256,162.4c-52,0-93.6,41.6-93.6,93.6 0,52 41.6,93.6 93.6,93.6s93.6-41.6 93.6-93.6c0-52-41.6-93.6-93.6-93.6zm0,166.4c-40.6,0-72.8-32.3-72.8-72.8s32.3-72.8 72.8-72.8 72.8,32.3 72.8,72.8-32.2,72.8-72.8,72.8z"/>
                    <path d="m256,214.4v20.8c11.4,0 20.8,9.4 20.8,20.8s-9.4,20.8-20.8,20.8-20.8-9.4-20.8-20.8h-20.8c0,22.9 18.7,41.6 41.6,41.6 22.9,0 41.6-18.7 41.6-41.6s-18.7-41.6-41.6-41.6z"/>
                  </g>
                </g>
              </svg>
            </div>
          </a>
          <%= link_to collection_path(id: bid.collection.address,bid_tab: true),:class=>"image_link" do %>
            <%= image_tag cover_image.blob.variant(resize_to_limit: [180, 202]) %>
          <% end %>
        </div>
        <div class="activity__content">
          <h3 class="activity__title d-flex align-items-start justify-content-between flex-column flex-md-row align-items-md-center">
            <%= link_to collection_path(id: bid.collection.address,bid_tab: true) do %>
              <%= bid.collection.title %>
            <% end %>
          </h3>
          <p class="activity__text">
            <%if params[:filters].eql?('owner_bid') || (bid.collection.creator_id != bid.collection.owner_id) || (bid.collection.creator_id == current_user.id) %>
              <%= 'Bid received from' %>
            <%elsif params[:filters].eql?('bid') || bid.collection.creator_id == bid.collection.owner_id %>
              <%= 'Bid placed by me' %>
            <%end%>
            <br>
            <%= link_to link_to_user(bid.user) do %> 
              @<%= bid.user.full_name %>
            <% end %>  <br>for <%= bid.crypto_currency %> <%= bid.crypto_currency_type %> </p>
            <span class="activity__time"><%= time_ago_in_words(activity.created_at) %> </span>
          <% if current_user.present? %>
            <%= select_tag :custom_tab_id, options_for_select(custom_tab_options, custom_tab&.id), { prompt: "--Select--", class: 'activity_select', data: { item_id: activity.item.collection.id, item_type: 'nft'  } } %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="col-md-4 col-sm-4 col-xs-12">
        <%= render "thumbnail_collection", collection: bid.collection, sold_text: false %>
      </div>
    <% end %>

  <% else %>
    <% if ["approved", "expired"].include?(activity.changeset["state"].last) %>
      <%if @thumbnail_type.eql?('mini_thumbnail') %>
        <div class="activity">
          <div class="activity__cover <%= @thumbnail_type.eql?('mini_thumbnail') ? '' : 'thumbnail_cover' %>">
            <a class="lightbox" href="<%= url_for(cover_image) %>" data-lightbox="image-1">
              <div class="lightbox_custom ">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 512 512">
                  <g>
                    <g>
                      <path d="m499.4,250.8c-51-86.3-143.6-140.4-243.4-140.4s-192.5,54.1-243.4,140.4c-2.1,3.1-2.1,7.3 5.32907e-15,10.4 51,86.3 143.6,140.4 243.4,140.4s192.5-54.1 243.4-140.4c2.1-3.1 2.1-7.3 0-10.4zm-243.4,130c-90.5,0-174.8-47.8-221.6-124.8 46.8-77 131.1-124.8 221.6-124.8s174.8,47.8 221.6,124.8c-46.8,77-131.1,124.8-221.6,124.8z"/>
                      <path d="m256,162.4c-52,0-93.6,41.6-93.6,93.6 0,52 41.6,93.6 93.6,93.6s93.6-41.6 93.6-93.6c0-52-41.6-93.6-93.6-93.6zm0,166.4c-40.6,0-72.8-32.3-72.8-72.8s32.3-72.8 72.8-72.8 72.8,32.3 72.8,72.8-32.2,72.8-72.8,72.8z"/>
                      <path d="m256,214.4v20.8c11.4,0 20.8,9.4 20.8,20.8s-9.4,20.8-20.8,20.8-20.8-9.4-20.8-20.8h-20.8c0,22.9 18.7,41.6 41.6,41.6 22.9,0 41.6-18.7 41.6-41.6s-18.7-41.6-41.6-41.6z"/>
                    </g>
                  </g>
                </svg>
              </div>
            </a>
            <%= link_to collection_path(id: bid.collection.address,bid_tab: true),:class=>"image_link" do %>
              <%= image_tag url_for(cover_image),:size=>"140x162" %>
            <% end %>
          </div>
          <div class="activity__content">
            <h3 class="activity__title d-flex align-items-start justify-content-between flex-column flex-md-row align-items-md-center">
              <%= link_to collection_path(id: bid.collection.address,bid_tab: true) do %>
                <%= bid.collection.title %>
              <% end %>
            </h3>
            <% if activity.changeset["state"].last == "approved" %>
              <p class="activity__text">Accepted by
                <%= link_to link_to_user(bid.owner) do %>
                  @<%= bid.owner.full_name %>
                <% end %>  <br>for <%= bid.crypto_currency %> <%= bid.crypto_currency_type %>
              </p>
              <span class="activity__time"><%= time_ago_in_words(activity.created_at) %> </span>
              <% if current_user.present? %>
                <%= select_tag :custom_tab_id, options_for_select(custom_tab_options, custom_tab&.id), { prompt: "--Select--", class: 'activity_select', data: { item_id: activity.item.collection.id, item_type: 'nft'  } } %>
              <% end %>
            <% end %>
            <% if activity.changeset["state"].last == "expired" %>
            <p class="activity__text">Expired by
              <%= link_to link_to_user(bid.owner) do %>
                @<%= bid.owner.full_name %>
              <% end %><br>for <%= bid.crypto_currency %> <%= bid.crypto_currency_type %>
            </p>
            <span class="activity__time"><%= time_ago_in_words(activity.created_at) %></span>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="col-md-4 col-sm-4 col-xs-12">
          <%= render "thumbnail_collection", collection: bid.collection, sold_text: false %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/activities/_collection_history_activity.html.erb
<div class="asset__action asset__action--verified">
  <%= link_to link_to_user(transaction.seller), class:"user_img" do %>
    <%= image_tag url_for(transaction.seller.profile_image(:icon)) %>
  <% end %>
  <p class="content_details">
  	<% if transaction.collection.multiple? %>
      @<%= link_to transaction.seller.full_name, link_to_user(transaction.seller) %> transfered 
      <% if transaction.quantity > 0 %>
        <%= transaction.quantity.to_i %> <%= transaction.quantity.to_i > 1 ? 'editions' : 'editions' %>&nbsp; for <%= transaction.currency %> <%= transaction.currency_type %>
        <br>
        <%= time_ago_in_words(transaction.created_at) %> ago
      <% else %>
        for <%= transaction.currency %> <%= transaction.currency_type %>
        <br>
        <%= time_ago_in_words(transaction.created_at) %> ago
      <% end %>
    <% else %>
      Transfered <%= time_ago_in_words(transaction.created_at) %> ago from <%= transaction.seller.full_name %> <br>to @<%= link_to transaction.buyer.full_name, link_to_user(transaction.buyer) %>&nbsp; &nbsp; for <%= transaction.currency %> <%= transaction.currency_type %>
    <% end %>
  </p>
</div>

app/views/activities/_custom_tab.html.erb
<% if current_user.present? && current_user.custom_tabs.present? %>
  <% current_user.custom_tabs.each do |custom_tab|%>
    <li>
      <input id="<%= custom_tab.tab_name %>" type="checkbox" name="custom_tab[]"  <%= (is_filter_active(params[:filters], "custom_tab_#{custom_tab.id}") == 'active') ? "checked='true'" : '' %> onclick="window.location.href ='<%= activities_path(activity_type: "activity", filters: "custom_tab_#{custom_tab.id}", thumbnail_type: @thumbnail_type ) %>'">
      <label for="<%= custom_tab.tab_name %>"><%= custom_tab.tab_name %> <%= ApplicationController.helpers.get_actual_count("activity", current_user, "custom_tab_#{custom_tab.id}") > 0 ? "(#{ApplicationController.helpers.get_actual_count("activity", current_user, "custom_tab_#{custom_tab.id}")})" : "" %></label>
      <% if !custom_tab.activity_custom_tabs.present? && custom_tab.tab_name != 'Discarded'%>
        <%= link_to remove_custom_tab_path(tab_id: custom_tab.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'trash_link' do %>
          <i class="fa fa-trash"></i>
        <% end %>
      <%end%>
    </li>
  <% end %>
<% end %>

app/views/activities/_custom_tab_form.html.erb
<div id="customTabForm" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title share_link_page_h4"><%= t("activities.filter_head") %></h4>
  <%= form_tag create_custom_tab_path do %>
    <div class="modal-body">
      <div class="row mb-15">
        <div class="col-md-12">
          <div class="form-group">
            <label for="full_name"><%= t("activities.name_head") %></label>
            <%= text_field_tag "tab_name", nil, class: 'form-control sign__input', placeholder: t("activities.name_head"), required: true %>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer text-center">
      <%=submit_tag 'Create', class: "btn buy-now bidding-element-btn theme-btn"%>
    </div>
  <% end %>
</div>

app/views/activities/_like.html.erb
<% if activity.event == "create" && activity.item.user.present? && activity.item.collection.present? %>
  <% custom_tab = selected_tab(current_user, activity.item.collection) %>
  <% custom_tab_options = current_user.custom_tabs.map{|u| [u.tab_name, u.id]} %>
  <% custom_tab_options << ['Show', 'show'] if custom_tab&.tab_name == 'Discarded' %>
  <% cover_image = activity.item.collection.cover.present? ? activity.item.collection.cover : activity.item.collection.attachment %>
  <%if @thumbnail_type.eql?('mini_thumbnail') %>
    <div class="activity">
      <div class="activity__cover">
        <a class="lightbox" href="<%= url_for(cover_image) %>" data-lightbox="image-1">
          <div class="lightbox_custom ">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 512 512">
              <g>
                <g>
                  <path d="m499.4,250.8c-51-86.3-143.6-140.4-243.4-140.4s-192.5,54.1-243.4,140.4c-2.1,3.1-2.1,7.3 5.32907e-15,10.4 51,86.3 143.6,140.4 243.4,140.4s192.5-54.1 243.4-140.4c2.1-3.1 2.1-7.3 0-10.4zm-243.4,130c-90.5,0-174.8-47.8-221.6-124.8 46.8-77 131.1-124.8 221.6-124.8s174.8,47.8 221.6,124.8c-46.8,77-131.1,124.8-221.6,124.8z"/>
                  <path d="m256,162.4c-52,0-93.6,41.6-93.6,93.6 0,52 41.6,93.6 93.6,93.6s93.6-41.6 93.6-93.6c0-52-41.6-93.6-93.6-93.6zm0,166.4c-40.6,0-72.8-32.3-72.8-72.8s32.3-72.8 72.8-72.8 72.8,32.3 72.8,72.8-32.2,72.8-72.8,72.8z"/>
                  <path d="m256,214.4v20.8c11.4,0 20.8,9.4 20.8,20.8s-9.4,20.8-20.8,20.8-20.8-9.4-20.8-20.8h-20.8c0,22.9 18.7,41.6 41.6,41.6 22.9,0 41.6-18.7 41.6-41.6s-18.7-41.6-41.6-41.6z"/>
                </g>
              </g>
            </svg>
          </div>
        </a>
        <%= link_to collection_path(activity.item.collection.address),:class=>"image_link" do %>
          <%= image_tag cover_image.blob.variant(resize_to_limit: [180, 202]) %>
        <% end %>
      </div>
      <div class="activity__content">
        <h3 class="activity__title d-flex align-items-start justify-content-between flex-column flex-md-row align-items-md-center">
          <%= link_to collection_path(activity.item.collection.address) do %>
            <%= activity.item.collection.title %>
          <% end %>
        </h3>
        <p class="activity__text">liked by
          <%= link_to link_to_user(activity.item.user) do %>
            @<%= activity.item.user.full_name %>
          <% end %>  <br>
          <span class="activity__time"><%= time_ago_in_words(activity.created_at) %> </span></p>
        <% if current_user.present? %>
          <%= select_tag :custom_tab_id, options_for_select(custom_tab_options, custom_tab&.id), { prompt: "--Select--", class: 'activity_select', data: { item_id: activity.item.collection.id, item_type: 'nft'  } } %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="col-md-4 col-sm-4 col-xs-12">
      <%= render "thumbnail_collection", collection: activity.item.collection, sold_text: false %>
    </div>
  <% end %>
<% end %>

app/views/activities/_own_contract.html.erb
<%hidden_field_tag "contract_address", contract.address%>

<div class="featured-creators-box cluster-box activity" style="margin-top: 20px">
  <%if params[:controller].eql?('users') && params[:action].eql?('show') && !contract.collections.unscoped.where(nft_contract_id: contract.id, state: :approved).present?%>
    <%= link_to remove_nft_contract_users_path(id: @user&.address, nft_id: contract.id, page_no: @page_no), method: :delete, data: { confirm: 'Are you sure?' }, class: 'trash_link' do %>
      <i class="fa fa-trash"></i>
    <% end %>
  <%end%>
  <a href="<%= nft_contract_path(contract.address)%>" class="activity_link">
      <div class="featured-creators-box-img">
          <div class="featured-creators-box-img-bg" style="background-image:url('<%=contract.cover_url(:banner)%>')">
          <img src="<%=contract.cover_url(:banner)%>;" class="img-responsive">
          </div>
          <div class="featured-creators-box-img-profile">
          <img src="<%=contract.attachment_url(:circle)%>" class="img-responsive">
          </div>
      </div>
      <div class="featured-creators-box-content h-80">
          <h4><%=contract.name%></h4>
          <p><%=contract.description%></p>
      </div>
  </a>
</div>

app/views/activities/_thumbnail_collection.html.erb
<% collection_attachment = collection.get_attachment(current_user)%>
<div class="card">
  <div class="t_c">
    <a href="<%= collection_path(collection.address)%>" class="card__cover" target='_blank'>
      <span class="collection-card-img" style="background-image: url('<%= cover_url(collection, :card) %>')">
        <%= image_tag cover_url(collection, :card)%>
      </span>
    </a>
  </div>
  <div class="grid-box">
    <h3 class="card__title" data-toggle="tooltip" data-placement="top" title="<%= collection.name %>">
      <a target='_blank' href="<%= collection_path(collection.address)%>"><%= collection.name %></a><% if collection.total_editions.present? %><span><%= collection.total_editions(:card).html_safe %></span><% end %>
    </h3>

    <div class="card__author custom_card__author">
      <div class="author__image_wraper">
        <div class="user_img">
          <%= image_tag collection.owner.profile_image(:icon) %>
          <a target='_blank' href="<%= link_to_user(collection.owner) %>" data-toggle="tooltip" data-placement="top" title="@<%= collection.owner.full_name%>">@<%= collection.owner.full_name%></a>
          <% if collection.owner.is_verified.present? %>
            <div class="sdk_tool" data-toggle="tooltip" data-placement="top" data-tooltip="CC : Certified Creator 
This Creator has sent Matic.art hers/his Identity Documents. 
To Become a CC: nft@matic.art" class="verified_badge_col"><%= image_tag 'verified_badge.png', class: 'image_resolution' %></div>
          <% end %>
        </div>
        <%if sold_text %>
          <div class="sold_out">SOLD</div>
        <% end %>
      </div>
      <div class="price__wrapper">
        <% if collection.instant_sale_enabled #|| collection.max_bid %>
          <% price, currency = collection.sale_price %>
          <div class="price" title="MATIC / wMATIC"><%= image_tag 'polygon_logo.png', alt: 'currency', class: 'currency_icon' %> <%= number_to_currency(price, precision: 3, :unit => '') %><%#= currency %></div>
          <div class="usd">$<%= number_to_currency(collection.sale_price_to_fiat(price, currency), precision: 2, :unit => '') %></div>
        <% end %>
      </div>
    </div>
    <div class="calltoaction__wrapper">
      <div class="royalty_price">
        <%if collection.royalty > 0 && !sold_text %>
          RYLTY: <%=collection.royalty%>%
        <%end%>
      </div>
      <% if collection.video_nft %>
        <%= link_to collection_path(collection.address), class: 'center_icon', target: '_blank' do %>
          <i data-toggle="tooltip" data-placement="top" title="Movie" class="fa fa-play-circle-o"></i>
        <% end %>
      <% end %>
      <div class="sale_text"><%= collection.put_on_sale ? 'on sale' : 'not on sale' %></div>
    </div>
  </div>
  <!-- <div class="card__info">
    <div class="card__price">
      <span><%#= t('shared.reserve_price')%></span>
      <%# if collection.instant_sale_price%>
       <span><%=collection.instant_sale_price%> MATIC</span>  
      <%# else %>
        <%# if collection.max_bid %>
          <p class="bid_status">Highest bid <b><%#= collection.max_bid.value %></b></p>
        <%#else%>
          <span>No active Bids</span> 
        <%# end %>
      <%#end%>
    </div>
  </div> -->
</div>

app/views/activities/assign_tab_to_activity.js.erb
$(".show_icon").html("<%=j render 'activities/custom_tab' %>");

app/views/activities/index.js.erb
$("#load_more_activities").append("<%=j render 'activities' %>");
<% if @activities.next_page.present? %>
  $("#load_more_activity").attr("href", "<%= activities_path(filters: params[:filters], page_no: @activities.next_page, activity_type: params[:activity_type]) %>");
<% else %>
  $(".load_more_section").remove();
<% end %>